### ISSUE TITLE
Only one url for ddi schema reference is too restrictive (Feedback PROGEDO)

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cmv#128]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

From Genevieve Michaud:

I have a small issue with CMV, regarding the very first line of any Document I upload, It pops up an error related to an addtionnal s \(https in place of http\) in the following string \('ddi:codebook:2\_5 [https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd](https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd)' is not equal to fixed value 'ddi:codebook:2\_5 [http://www.ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd](http://www.ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd)' in '/codeBook/@&zwnj;xsi:schemaLocation' \(lineNumber: 1\). Could this constraint be lowered as a warning? What do you think?

Just copying her comment.

**Comment by matthew-morris-cessda** [comment]
This is a profile issue
