### ISSUE TITLE
Documentation should mention jar availability

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cmv#131]
**Original report on BitBucket by Carsten Thiel (GitHub: [schildwaechter](https://github.com/schildwaechter)).**

----------------------------------------

The current documentation does not mention the possibility to use the jar, this should be added including the reference to the use.

**Comment by matthew-morris-cessda** [comment]
Documentation now mentions how to import the JAR into a new Java application
