### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cmv#142]
Release docs are here: https://drive.google.com/drive/folders/1jhIaluVKyPHmHuAN0H23FFa7v90TZ16z?usp=share_link

**Comment by john-shepherdson** [comment]
I need to add some non-functional files to the repo to improve the SQAaaS score and reserve a DOI and add it to the changelog before release.

**Comment by john-shepherdson** [comment]
Please ensure it is not released as a snapshot

**Comment by matthew-morris-cessda** [comment]
All tickets have been closed

**Comment by john-shepherdson** [comment]
I am working on cmv.core. Hold back on release.

**Comment by matthew-morris-cessda** [comment]
There is an issue (https://github.com/cessda/cessda.cmv.documentation/issues/21) that still needs to be resolved.

**Comment by john-shepherdson** [comment]
Release approved

**Comment by matthew-morris-cessda** [comment]
Release commits tagged (v1.0.0)

**Comment by matthew-morris-cessda** [comment]
New version iteration started, closed 1.0.0 milestones

**Comment by matthew-morris-cessda** [comment]
Release completed
