### ISSUE TITLE
Release v 1.1.0 to production

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cmv#171]
Components released (ensure version numbers are updated for each):

- [x] cessda.cmv.core
- [x] cessda.cmv.documentation
- [x] cessda.cmv.server

**Comment by matthew-morris-cessda** [comment]
I've added the list of components to be released to the issue description

**Comment by matthew-morris-cessda** [comment]
Blocked on https://github.com/cessda/cessda.cmv.core/pull/143

**Comment by matthew-morris-cessda** [comment]
CMV 1.1.0 has been released to production
