### ISSUE TITLE
Staging instance for UI testing?

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cmv#71]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

In a CVS meeting, Carsten said that the policy CESSDA is adopting is that dev instances are meant for developer testing and staging instances for user testing. So I wonder if there would need to be a staging instance of CMV?

**Comment by matthew-morris-cessda** [comment]
Automated staging deployments now occur.
