### ISSUE TITLE
Put the zenodo link to the DDI Codebook Profiles in the Documentation

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cmv#96]
**Original report on BitBucket by Alexander Mühlbauer.**

----------------------------------------

* See feedback mail [https://github.com/cessda/cessda.cmv/issues/97](https://github.com/cessda/cessda.cmv/issues/97)

‌

**Comment by matthew-morris-cessda** [comment]
@john-shepherdson Do you have a link to the Zenodo records of the DDI profiles?

**Comment by john-shepherdson** [comment]
DDI Codebook 1.0.4: DOI 10.5281/zenodo.4580376
